New Contributor Hex-24
codeforcauseorg/pledge pull request #121
Opened 2020-10-03 10:48 UTC by ashis-solomon

Added contributor

2020-10-03 16:51 UTC, Abhishek-kumar09 reviewed
I guess you have some problem in naming the json file, otherwise everything looks good and still build is failing.

2020-10-03 17:02 UTC, ashis-solomon commented
> I guess you have some problem in naming the json file, otherwise everything looks good and still build is failing.

Thanks Abhishek ....new to github

2020-10-18 07:29 UTC, Abhishek-kumar09 requested changes

2020-10-18 07:29 UTC, Abhishek-kumar09 commented on src/data/contributors/Hex-24.json
> +  "twitter": "https://twitter.com/Hex-24,
@ashis-solomon just remove the comma from the last last json object and your code will run fine. I guess there is a bug in gatsby json parser.

2021-03-03 09:48 UTC, closed without merging