Ayush New Contributor
codeforcauseorg/pledge pull request #192
Opened 2020-12-20 15:42 UTC by CyberBoyAyush

2020-12-20 15:44 UTC, CyberBoyAyush commented
**My First Step Towards Open Source Contributions**

2020-12-22 07:24 UTC, Abhishek-kumar09 requested changes

2020-12-22 07:24 UTC, Abhishek-kumar09 commented on src/data/contributors/CyberBoyAyush.json
> +    "cause" : "I Code For Knowledge And Passion",
I code for is already the part of the pre-written string.

2020-12-22 07:28 UTC, Abhishek-kumar09 commented
Thanks for the quick changes @CyberBoyAyush,  
> My First Step Towards Open Source Contributions

Giving you lots of good luck and best wishes.

2020-12-22 07:28 UTC, merged