Sarthak Srivastav made changes
codeforcauseorg/pledge pull request #365
Opened 2021-03-03 06:04 UTC by SarthakSrivastav

Please merge my 'temp' branch in your master branch and deploy it on your site, so that I feel more confident and move my next step towards opensource contribution.

2021-03-09 07:26 UTC, kaiwalyakoparkar requested changes
Maximum 3 skills should be added. Refer : https://github.com/codeforcauseorg/pledge/blob/main/hints/create_pledge.md . 3rd point

2021-03-09 07:47 UTC, closed without merging

2021-03-09 07:52 UTC, SarthakSrivastav commented
Hi Kaiwalya Koparkar,

2021-03-09 07:54 UTC, SarthakSrivastav commented
Hey Kaiwalya now I modified my Skills data in the repo and successfully commit it, will you please review and merge it.

2021-03-09 07:58 UTC, SarthakSrivastav commented
Hey Codeforcauseorg/Pledge, I made the required changes in the file will
you please review and merge it now.

On Tue, Mar 9, 2021 at 12:57 PM Kaiwalya Koparkar <notifications@github.com>
wrote:

> *@kaiwalyakoparkar* requested changes on this pull request.
>
> Maximum 3 skills should be added. Refer :
> https://github.com/codeforcauseorg/pledge/blob/main/hints/create_pledge.md
> . 3rd point
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeforcauseorg/pledge/pull/365#pullrequestreview-607090754>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APWE47XGBCUW5OPE2TFHZUDTCXEURANCNFSM4YQSWL3Q>
> .
>

2021-03-09 09:50 UTC, kaiwalyakoparkar approved these changes
LGTM

2021-03-09 09:51 UTC, kaiwalyakoparkar commented
Hey Sarthak, I don't have the rights to merge the pull request.. but I have reviewed and approved your request

2021-03-09 10:04 UTC, SarthakSrivastav commented
Okay, Thanks.

2021-06-29 06:00 UTC, shreyshreyansh commented on src/data/contributors/SarthakSrivastav.json
> +{
Looks good to go