new contributor made change
codeforcauseorg/pledge pull request #429
Opened 2021-03-28 09:37 UTC by ARSHADKHAN615

Please Marge my Code

2021-03-30 04:50 UTC, Suyash-Purwar requested changes
Hey,

Please revert the changes made in the file Aaditya.json. You are only allowed to add your data in a new file. Your PR will be merged after the requested changes.

2021-03-30 05:18 UTC, Akshay-Dongare approved these changes

2021-03-31 06:16 UTC, ARSHADKHAN615 commented
I am not change any file ,brother
Please See it.
That change is visible only because of code formatting.

2021-03-31 06:18 UTC, ARSHADKHAN615 commented
Please Merge My Code.

2022-05-26 14:01 UTC, closed without merging