my first ever contribution
codeforcauseorg/pledge pull request #93
Opened 2020-09-05 05:50 UTC by nausherofficial

thank you anuj garg and code for cause team to provide me this opportunity to contribute a open source project

2020-09-05 18:21 UTC, Abhishek-kumar09 requested changes

2020-09-05 18:21 UTC, Abhishek-kumar09 commented on src/data/contributors/nausherali.json
> +    "cause": "serve humanity ",
What a great cause to code :) Just a small suggestion.
![image](https://user-images.githubusercontent.com/48255244/92311169-697a1300-efd2-11ea-94c9-9fabf2431e07.png)
I think `I code for serving humanity` is gramatically more accurate.

2020-09-05 22:43 UTC, nausherofficial commented
Got it

On Sat, Sep 5, 2020, 23:51 Abhishek Kumar <notifications@github.com> wrote:

> *@Abhishek-kumar09* requested changes on this pull request.
> ------------------------------
>
> In src/data/contributors/nausherali.json
> <https://github.com/codeforcauseorg/pledge/pull/93#discussion_r483975261>:
>
> > @@ -0,0 +1,10 @@
> +{
> +    "name": "Nausher Ali",
> +    "skills": ["MERN", "Django", "Spring"],
> +    "cause": "serve humanity ",
>
> What a great cause to code :) Just a small suggestion.
> [image: image]
> <https://user-images.githubusercontent.com/48255244/92311169-697a1300-efd2-11ea-94c9-9fabf2431e07.png>
> I think I code for serving humanity is gramatically more accurate.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeforcauseorg/pledge/pull/93#pullrequestreview-483071100>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANL4VMP35MBLIISCRY4RXH3SEJ6RTANCNFSM4Q2OEZSA>
> .
>

2020-09-05 23:15 UTC, nausherofficial reviewed
changes applied

2020-09-06 07:33 UTC, Abhishek-kumar09 approved these changes

2020-09-06 07:34 UTC, merged

2020-09-06 07:35 UTC, Abhishek-kumar09 commented
Thanks for your PR @nausherofficial . Welcome to @codeforcauseorg.

2020-09-06 07:41 UTC, nausherofficial commented
> Thanks for your PR @nausherofficial . Welcome to @codeforcauseorg.

thank you so much @Abhishek-kumar09 .