Added my Pledge
codeforcauseorg/pledge pull request #98
Opened 2020-09-11 13:41 UTC by sneha1827

2020-09-13 18:24 UTC, Abhishek-kumar09 requested changes

2020-09-13 18:24 UTC, Abhishek-kumar09 commented on src/data/contributors/sneha1827
> +{
@sneha1827, The file-name is wrong. It should be a `json`.  Just rename it to `sneha1827.json`, else is great.

2020-09-14 09:26 UTC, sneha1827 commented
I have renamed my filename to sneha1827.json
Thank you!

2020-09-14 09:48 UTC, Abhishek-kumar09 commented
Great!, thanks for your PR. Welcome to the community :1st_place_medal:

2020-09-14 09:49 UTC, merged